spring.application.name=cine-estrella
server.port=8081
# ===== BASE DE DATOS H2 =====
spring.datasource.url=jdbc:h2:mem:cine-estrella
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== JPA / HIBERNATE =====
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# ===== CONSOLA H2 (para ver tablas en el navegador) =====
spring.h2-console.enabled=true
spring.h2-console.path=/h2-console

# ===== FORMATO JSON =====
spring.jackson.serialization.indent_output=true

# ===== DATOS INICIALES =====
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
